#!/bin/sh
#
# Clone all Apache repositories
#

cd ~/data/apache

curl -s 'http://git.apache.org/' |
sed -n 's|.*\(https://github.com/apache/[^"]*\)".*|\1|p' |
sed 's|\(.*\)/\([^/]*\)|\1/\2 \2|' |
while read url dir ; do
  if ! [ -d $dir ] ; then
    echo $dir
    git clone $url
  fi
done
