#!/bin/bash
#
# Clone all GNU Savannah git repositories
#

curl http://git.savannah.gnu.org/gitweb/ |
sed -n 's|.*>\([^<]*.git\)<.*|git://git.savannah.gnu.org/\1|p' |
fgrep -v -f <(ls | sed 's/$/.git/') |
xargs -n 1 git clone
