#!/bin/sh
#
# Measure all Subversion repositories in the specified collection
#

COLLECTION="$1"

if [ "$COLLECTION" = '' ]
then
	echo "Usage: $0 collection-name" 1>&2
	exit 1
fi

rm -rf $HOME/src/cagr/data/$COLLECTION
mkdir $HOME/src/cagr/data/$COLLECTION

export LC_CTYPE=en_US.UTF-8 

find $HOME/data/$COLLECTION/ -mindepth 1 -maxdepth 1 -type d |
while read repo
do
	name=`basename $repo`
	if ! svn list file://$repo | grep '^trunk/$' >/dev/null ; then
	  echo "Skipping $repo due to a lack of top-level trunk"
	  continue
	fi
	echo "Measuring $name"
	cd /tmp
	svn co file://$repo
	cd /tmp/$name
	START=$(svn log --xml |
	sed -n 's|^<date>\(....-..-..\).*</date>|\1|p' |
	sort |
	head -1 )
	$HOME/src/cagr/tools/measure svn $START 12 >$HOME/src/cagr/data/$COLLECTION/$name.csv
	cd /tmp
	rm -rf /tmp/$name
done
